apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: wv3m7gum8-go
  janus-idp.io/tekton: wv3m7gum8-go
  backstage.io/kubernetes-id: wv3m7gum8-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wv3m7gum8-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
